version: '3.8'

services:
  lego_club:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8300:8300"
    volumes:
      - ./backend/lego_club.db:/app/lego_club.db  # <-- Seule la base de données est persistée
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped